I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 362, in script
    "Halfway up the mountain, he comes across a lake with a corpse lying on its shore.
Exception: Sayer '"Halfway up the mountain, he comes across a lake with a corpse lying on its shore.
    There is no way to tell how long it has been there, but when he investigates
    the body, he finds a note in the pocket."' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 362, in script
    "Halfway up the mountain, he comes across a lake with a corpse lying on its shore.
  File "C:\Users\ranaf\Documents\renpy-8.3.2-sdk\renpy\ast.py", line 2573, in execute
    Say.execute(self)
  File "C:\Users\ranaf\Documents\renpy-8.3.2-sdk\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\ranaf\Documents\renpy-8.3.2-sdk\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer '"Halfway up the mountain, he comes across a lake with a corpse lying on its shore.
    There is no way to tell how long it has been there, but when he investigates
    the body, he finds a note in the pocket."' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.2.24090902
Test 1.0
Thu Nov  7 21:27:57 2024
